ALTER TABLE "CultureItem" ADD COLUMN IF NOT EXISTS "coverImage" TEXT;
ALTER TABLE "CultureItem" ADD COLUMN IF NOT EXISTS "featuredOnCatalog" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CultureItem" ADD COLUMN IF NOT EXISTS "mediaContent" JSONB;
